//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eticaretproje1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uyesözleşmesi
    {
        public int Id { get; set; }
        public string İcerik { get; set; }
        public string Baslik { get; set; }
        public string Anahtar_Kelime { get; set; }
        public string Title { get; set; }
    }
}
